package com.raven.all;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author allen
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;

public class ForgetPass extends javax.swing.JFrame {

    /**
     * Creates new form ForgetPass
     */
    public class DatabaseConnection {
        // Database URL, username, and password

        private static final String URL = "jdbc:mysql://localhost:3306/waterstation";
        private static final String USER = "root";
        private static final String PASSWORD = "";

        // Method to establish a connection to the database
        public static Connection getConnection() {
            Connection connection = null;
            try {
                // Register the JDBC driver
                Class.forName("com.mysql.cj.jdbc.Driver");
                // Open a connection
                connection = DriverManager.getConnection(URL, USER, PASSWORD);
                System.out.println("Database connected successfully.");
            } catch (ClassNotFoundException e) {
                System.out.println("MySQL JDBC Driver not found.");
                e.printStackTrace();
            } catch (SQLException e) {
                System.out.println("Failed to connect to the database.");
                e.printStackTrace();
            }
            return connection;
        }
    }

    public ForgetPass() {
        initComponents();

        ((AbstractDocument) OTPField.getDocument()).setDocumentFilter(new DocumentFilter() {
            @Override
            public void replace(FilterBypass fb, int offset, int length, String text, AttributeSet attrs) throws BadLocationException {
                String currentText = fb.getDocument().getText(0, fb.getDocument().getLength());
                int futureLength = currentText.length() - length + text.length();
                if (futureLength <= 10) {
                    super.replace(fb, offset, length, text, attrs);
                } else {
                    // Optionally provide feedback to the user
                    // For example, beep or show an error message
                    java.awt.Toolkit.getDefaultToolkit().beep();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        SignUpUsernameLabel = new javax.swing.JLabel();
        EnterUsernameField = new javax.swing.JTextField();
        SignUpPassLabel = new javax.swing.JLabel();
        NewPasswordField = new javax.swing.JPasswordField();
        EnterOTPLabel = new javax.swing.JLabel();
        icon1 = new javax.swing.JLabel();
        icon2 = new javax.swing.JLabel();
        OTPField = new javax.swing.JPasswordField();
        DoneJButton = new javax.swing.JButton();
        BackJButton = new javax.swing.JButton();
        ForgetPassBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SignUpUsernameLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        SignUpUsernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        SignUpUsernameLabel.setText("Enter Current Username:");
        jLayeredPane1.add(SignUpUsernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, -1, -1));

        EnterUsernameField.setBackground(new java.awt.Color(223, 223, 223));
        EnterUsernameField.setForeground(new java.awt.Color(51, 51, 51));
        jLayeredPane1.add(EnterUsernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 390, 48));

        SignUpPassLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        SignUpPassLabel.setForeground(new java.awt.Color(255, 255, 255));
        SignUpPassLabel.setText("Enter New Password:");
        jLayeredPane1.add(SignUpPassLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, -1, -1));

        NewPasswordField.setBackground(new java.awt.Color(223, 223, 223));
        NewPasswordField.setForeground(new java.awt.Color(51, 51, 51));
        jLayeredPane1.add(NewPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 390, 48));

        EnterOTPLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        EnterOTPLabel.setForeground(new java.awt.Color(255, 255, 255));
        EnterOTPLabel.setText("Enter OTP:");
        jLayeredPane1.add(EnterOTPLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, -1, -1));

        icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/hide.png"))); // NOI18N
        icon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                icon1MousePressed(evt);
            }
        });
        jLayeredPane1.add(icon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 430, -1, -1));

        icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/seen.png"))); // NOI18N
        icon2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                icon2MousePressed(evt);
            }
        });
        jLayeredPane1.add(icon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 430, -1, -1));

        OTPField.setBackground(new java.awt.Color(223, 223, 223));
        OTPField.setForeground(new java.awt.Color(51, 51, 51));
        jLayeredPane1.add(OTPField, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, 240, 48));

        DoneJButton.setBackground(new java.awt.Color(153, 204, 255));
        DoneJButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        DoneJButton.setForeground(new java.awt.Color(0, 74, 173));
        DoneJButton.setText("Done");
        DoneJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneJButtonActionPerformed(evt);
            }
        });
        jLayeredPane1.add(DoneJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 510, 166, -1));

        BackJButton.setBackground(new java.awt.Color(153, 204, 255));
        BackJButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        BackJButton.setForeground(new java.awt.Color(0, 74, 173));
        BackJButton.setText("Back");
        BackJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackJButtonActionPerformed(evt);
            }
        });
        jLayeredPane1.add(BackJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 510, 166, -1));

        ForgetPassBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/ForgetPassBG.png"))); // NOI18N
        jLayeredPane1.add(ForgetPassBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DoneJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoneJButtonActionPerformed
        String username = EnterUsernameField.getText();
        String newPassword = NewPasswordField.getText();
        String otp = OTPField.getText();

        if (username.isEmpty() || newPassword.isEmpty() || otp.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill all fields", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try (Connection conn = DatabaseConnection.getConnection()) {
            String selectSql = "SELECT OTP FROM accounts WHERE username = ?";
            try (PreparedStatement selectStmt = conn.prepareStatement(selectSql)) {
                selectStmt.setString(1, username);
                ResultSet rs = selectStmt.executeQuery();
                if (rs.next()) {
                    String dbOTP = rs.getString("OTP");
                    if (dbOTP.equals(otp)) {
                        String updateSql = "UPDATE accounts SET password = ? WHERE username = ?";
                        try (PreparedStatement updateStmt = conn.prepareStatement(updateSql)) {
                            updateStmt.setString(1, newPassword);
                            updateStmt.setString(2, username);
                            updateStmt.executeUpdate();
                            JOptionPane.showMessageDialog(this, "Password updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Incorrect OTP!", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Username not found!", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_DoneJButtonActionPerformed

    private void BackJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackJButtonActionPerformed
        redirectToLoginPage();
    }//GEN-LAST:event_BackJButtonActionPerformed

    private void icon1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon1MousePressed

        icon1.setVisible(false);
        icon2.setVisible(true);
        OTPField.setEchoChar((char) 0);

    }//GEN-LAST:event_icon1MousePressed

    private void icon2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon2MousePressed

        icon2.setVisible(false);
        icon1.setVisible(true);
        OTPField.setEchoChar('*');;

    }//GEN-LAST:event_icon2MousePressed

    private void redirectToLoginPage() {
        Login LoginForm = new Login();
        LoginForm.setVisible(true);
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgetPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgetPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgetPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgetPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgetPass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackJButton;
    private javax.swing.JButton DoneJButton;
    private javax.swing.JLabel EnterOTPLabel;
    private javax.swing.JTextField EnterUsernameField;
    private javax.swing.JLabel ForgetPassBG;
    private javax.swing.JPasswordField NewPasswordField;
    private javax.swing.JPasswordField OTPField;
    private javax.swing.JLabel SignUpPassLabel;
    private javax.swing.JLabel SignUpUsernameLabel;
    private javax.swing.JLabel icon1;
    private javax.swing.JLabel icon2;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables
}
