/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ADMIN
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SignUpLayeredPane = new javax.swing.JLayeredPane();
        whitebg = new javax.swing.JPanel();
        LoginLabel = new javax.swing.JLabel();
        ConfirmPasswordLabel = new javax.swing.JLabel();
        SignUpUsernameLabel = new javax.swing.JLabel();
        SignUpUsernameField = new javax.swing.JTextField();
        SignUpPasswordField = new javax.swing.JPasswordField();
        SignUpButton = new javax.swing.JButton();
        SignUpPassLabel = new javax.swing.JLabel();
        ConfirmPassField = new javax.swing.JPasswordField();
        AccountReadyLabel = new javax.swing.JLabel();
        LogInRedirectButton = new javax.swing.JButton();
        ShowPassSignUp = new javax.swing.JCheckBox();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1280, 720));

        SignUpLayeredPane.setPreferredSize(new java.awt.Dimension(1280, 720));

        whitebg.setBackground(new java.awt.Color(255, 255, 255));
        whitebg.setForeground(new java.awt.Color(255, 255, 255));
        whitebg.setMaximumSize(new java.awt.Dimension(640, 1080));
        whitebg.setMinimumSize(new java.awt.Dimension(640, 720));

        LoginLabel.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        LoginLabel.setText("Create Account");
        LoginLabel.setMaximumSize(new java.awt.Dimension(355, 45));
        LoginLabel.setMinimumSize(new java.awt.Dimension(355, 45));
        LoginLabel.setPreferredSize(new java.awt.Dimension(355, 45));

        ConfirmPasswordLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        ConfirmPasswordLabel.setText("Confirm Password:");

        SignUpUsernameLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        SignUpUsernameLabel.setText("Enter Username:");

        SignUpButton.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        SignUpButton.setText("SIGN UP");
        SignUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpButtonActionPerformed(evt);
            }
        });

        SignUpPassLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        SignUpPassLabel.setText("Enter Password:");

        AccountReadyLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        AccountReadyLabel.setText("Have an account?");

        LogInRedirectButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        LogInRedirectButton.setText("LOGIN");
        LogInRedirectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInRedirectButtonActionPerformed(evt);
            }
        });

        ShowPassSignUp.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ShowPassSignUp.setText("Show Password");
        ShowPassSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowPassSignUpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout whitebgLayout = new javax.swing.GroupLayout(whitebg);
        whitebg.setLayout(whitebgLayout);
        whitebgLayout.setHorizontalGroup(
            whitebgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(whitebgLayout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(LoginLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(142, 142, 142))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, whitebgLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(whitebgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, whitebgLayout.createSequentialGroup()
                        .addGroup(whitebgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SignUpUsernameLabel)
                            .addComponent(SignUpPassLabel)
                            .addComponent(ConfirmPasswordLabel)
                            .addGroup(whitebgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(SignUpUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(SignUpPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ConfirmPassField, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ShowPassSignUp)))
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, whitebgLayout.createSequentialGroup()
                        .addComponent(SignUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(252, 252, 252))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, whitebgLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(whitebgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, whitebgLayout.createSequentialGroup()
                        .addComponent(LogInRedirectButton)
                        .addGap(273, 273, 273))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, whitebgLayout.createSequentialGroup()
                        .addComponent(AccountReadyLabel)
                        .addGap(237, 237, 237))))
        );
        whitebgLayout.setVerticalGroup(
            whitebgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(whitebgLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(LoginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(SignUpUsernameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SignUpUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(SignUpPassLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SignUpPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ConfirmPasswordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ConfirmPassField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(ShowPassSignUp)
                .addGap(17, 17, 17)
                .addComponent(SignUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(AccountReadyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LogInRedirectButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SignUpLayeredPane.setLayer(whitebg, javax.swing.JLayeredPane.PALETTE_LAYER);
        SignUpLayeredPane.add(whitebg);
        whitebg.setBounds(320, 50, 640, 680);
        SignUpLayeredPane.add(bg);
        bg.setBounds(1159, 123, 0, 0);

        getContentPane().add(SignUpLayeredPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SignUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpButtonActionPerformed

    }//GEN-LAST:event_SignUpButtonActionPerformed

    private void LogInRedirectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInRedirectButtonActionPerformed
        redirectToLogInPage();
    }//GEN-LAST:event_LogInRedirectButtonActionPerformed

    private void ShowPassSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowPassSignUpActionPerformed
        if (ShowPassSignUp.isSelected()) {
            SignUpPasswordField.setEchoChar((char) 0);
            ConfirmPassField.setEchoChar((char) 0);// Show password
        } else {
            SignUpPasswordField.setEchoChar('•');
            ConfirmPassField.setEchoChar('•');// Hide password (default char, can be '*')
        }
    }//GEN-LAST:event_ShowPassSignUpActionPerformed
    private void redirectToLogInPage() {
        Login LoginForm = new Login();
        LoginForm.setVisible(true);
        this.dispose();
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccountReadyLabel;
    private javax.swing.JPasswordField ConfirmPassField;
    private javax.swing.JLabel ConfirmPasswordLabel;
    private javax.swing.JButton LogInRedirectButton;
    private javax.swing.JLabel LoginLabel;
    private javax.swing.JCheckBox ShowPassSignUp;
    private javax.swing.JButton SignUpButton;
    private javax.swing.JLayeredPane SignUpLayeredPane;
    private javax.swing.JLabel SignUpPassLabel;
    private javax.swing.JPasswordField SignUpPasswordField;
    private javax.swing.JTextField SignUpUsernameField;
    private javax.swing.JLabel SignUpUsernameLabel;
    private javax.swing.JLabel bg;
    private javax.swing.JPanel whitebg;
    // End of variables declaration//GEN-END:variables
}
