import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.IntelliJTheme;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;


public class SignUp extends javax.swing.JFrame {
    
    

    public class DatabaseConnection {
    // Database URL, username, and password
    private static final String URL = "jdbc:mysql://localhost:3306/waterstation";
    private static final String USER = "root";
    private static final String PASSWORD = "";

    // Method to establish a connection to the database
    public static Connection getConnection() {
        Connection connection = null;
        try {
            // Register the JDBC driver
            Class.forName("com.mysql.cj.jdbc.Driver");
            // Open a connection
            connection = DriverManager.getConnection(URL, USER, PASSWORD);
            System.out.println("Database connected successfully.");
        } catch (ClassNotFoundException e) {
            System.out.println("MySQL JDBC Driver not found.");
            e.printStackTrace();
        } catch (SQLException e) {
            System.out.println("Failed to connect to the database.");
            e.printStackTrace();
        }
        return connection;
    }
    public static void closeConnection(Connection connection) {
        if (connection != null) {
            try {
                connection.close();
                System.out.println("Database connection closed.");
            } catch (SQLException e) {
                System.out.println("Failed to close the database connection.");
                e.printStackTrace();
            }
        }
    }
    }
    public SignUp() {
        initComponents();
        setTitle("Jentaime Water Station");
        setResizable(false);
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SignUpLayeredPane = new javax.swing.JLayeredPane();
        SignUpUsernameLabel = new javax.swing.JLabel();
        SignUpUsernameField = new javax.swing.JTextField();
        SignUpPassLabel = new javax.swing.JLabel();
        SignUpPasswordField = new javax.swing.JPasswordField();
        ConfirmPasswordLabel = new javax.swing.JLabel();
        ConfirmPassField = new javax.swing.JPasswordField();
        EnterOTPLabel = new javax.swing.JLabel();
        ShowPassSignUp = new javax.swing.JCheckBox();
        OTPField = new javax.swing.JPasswordField();
        SignUpButton = new javax.swing.JButton();
        AccountReadyLabel = new javax.swing.JLabel();
        SignUpbg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1280, 720));

        SignUpLayeredPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SignUpLayeredPane.setMaximumSize(new java.awt.Dimension(1920, 1080));
        SignUpLayeredPane.setMinimumSize(new java.awt.Dimension(1280, 720));

        SignUpUsernameLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        SignUpUsernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        SignUpUsernameLabel.setText("Enter Username:");
        SignUpLayeredPane.add(SignUpUsernameLabel);
        SignUpUsernameLabel.setBounds(480, 230, 149, 22);

        SignUpUsernameField.setBackground(new java.awt.Color(223, 223, 223));
        SignUpUsernameField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        SignUpUsernameField.setForeground(new java.awt.Color(102, 102, 102));
        SignUpLayeredPane.add(SignUpUsernameField);
        SignUpUsernameField.setBounds(520, 260, 240, 40);

        SignUpPassLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        SignUpPassLabel.setForeground(new java.awt.Color(255, 255, 255));
        SignUpPassLabel.setText("Enter Password:");
        SignUpLayeredPane.add(SignUpPassLabel);
        SignUpPassLabel.setBounds(480, 310, 188, 28);

        SignUpPasswordField.setBackground(new java.awt.Color(223, 223, 223));
        SignUpPasswordField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        SignUpPasswordField.setForeground(new java.awt.Color(102, 102, 102));
        SignUpLayeredPane.add(SignUpPasswordField);
        SignUpPasswordField.setBounds(520, 340, 240, 40);

        ConfirmPasswordLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ConfirmPasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        ConfirmPasswordLabel.setText("Confirm Password:");
        SignUpLayeredPane.add(ConfirmPasswordLabel);
        ConfirmPasswordLabel.setBounds(480, 390, 219, 28);

        ConfirmPassField.setBackground(new java.awt.Color(223, 223, 223));
        ConfirmPassField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        ConfirmPassField.setForeground(new java.awt.Color(102, 102, 102));
        SignUpLayeredPane.add(ConfirmPassField);
        ConfirmPassField.setBounds(520, 420, 240, 40);

        EnterOTPLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        EnterOTPLabel.setForeground(new java.awt.Color(255, 255, 255));
        EnterOTPLabel.setText("Enter OTP:");
        SignUpLayeredPane.add(EnterOTPLabel);
        EnterOTPLabel.setBounds(480, 470, 96, 22);

        ShowPassSignUp.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ShowPassSignUp.setForeground(new java.awt.Color(255, 255, 255));
        ShowPassSignUp.setText("Show Password");
        ShowPassSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowPassSignUpActionPerformed(evt);
            }
        });
        SignUpLayeredPane.add(ShowPassSignUp);
        ShowPassSignUp.setBounds(630, 460, 115, 19);

        OTPField.setBackground(new java.awt.Color(223, 223, 223));
        OTPField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        OTPField.setForeground(new java.awt.Color(102, 102, 102));
        SignUpLayeredPane.add(OTPField);
        OTPField.setBounds(520, 500, 240, 40);

        SignUpButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        SignUpButton.setForeground(new java.awt.Color(255, 255, 255));
        SignUpButton.setText("SIGN UP");
        SignUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpButtonActionPerformed(evt);
            }
        });
        SignUpLayeredPane.add(SignUpButton);
        SignUpButton.setBounds(565, 550, 150, 30);

        AccountReadyLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        AccountReadyLabel.setForeground(new java.awt.Color(255, 255, 255));
        AccountReadyLabel.setText("Have an account? LOG IN");
        AccountReadyLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccountReadyLabelMouseClicked(evt);
            }
        });
        SignUpLayeredPane.add(AccountReadyLabel);
        AccountReadyLabel.setBounds(525, 590, 230, 33);

        SignUpbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/SignupBG.png"))); // NOI18N
        SignUpLayeredPane.add(SignUpbg);
        SignUpbg.setBounds(0, 0, 1280, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SignUpLayeredPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SignUpLayeredPane, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SignUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpButtonActionPerformed
        String username = SignUpUsernameField.getText();
        String password1 = new String(SignUpPasswordField.getPassword());
        String password2 = new String(ConfirmPassField.getPassword());

        if (username.isEmpty() || password1.isEmpty() || password2.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill all fields", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!password1.equals(password2)) {
            JOptionPane.showMessageDialog(this, "Passwords do not match!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try (Connection conn = DatabaseConnection.getConnection()) {
            String sql = "INSERT INTO accounts (username, password) VALUES (?, ?)";
            try (PreparedStatement pstmt = conn.prepareStatement(sql)) {
                pstmt.setString(1, username);
                pstmt.setString(2, password1);
                pstmt.executeUpdate();
            }
            JOptionPane.showMessageDialog(this, "Sign up successful!", "Success", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_SignUpButtonActionPerformed

    private void ShowPassSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowPassSignUpActionPerformed
       if (ShowPassSignUp.isSelected()) {
            SignUpPasswordField.setEchoChar((char) 0);
            ConfirmPassField.setEchoChar((char) 0);// Show password
        } else {
            SignUpPasswordField.setEchoChar('•');
            ConfirmPassField.setEchoChar('•');// Hide password (default char, can be '*')
        }
    }//GEN-LAST:event_ShowPassSignUpActionPerformed

    private void AccountReadyLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccountReadyLabelMouseClicked
        redirectToLogInPage();
    }//GEN-LAST:event_AccountReadyLabelMouseClicked
    private void redirectToLogInPage() {
        Login LoginForm = new Login();
        LoginForm.setVisible(true);
        this.dispose();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        IntelliJTheme.setup(SignUp.class.getResourceAsStream("/template.theme.json"));
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccountReadyLabel;
    private javax.swing.JPasswordField ConfirmPassField;
    private javax.swing.JLabel ConfirmPasswordLabel;
    private javax.swing.JLabel EnterOTPLabel;
    private javax.swing.JPasswordField OTPField;
    private javax.swing.JCheckBox ShowPassSignUp;
    private javax.swing.JButton SignUpButton;
    private javax.swing.JLayeredPane SignUpLayeredPane;
    private javax.swing.JLabel SignUpPassLabel;
    private javax.swing.JPasswordField SignUpPasswordField;
    private javax.swing.JTextField SignUpUsernameField;
    private javax.swing.JLabel SignUpUsernameLabel;
    private javax.swing.JLabel SignUpbg;
    // End of variables declaration//GEN-END:variables
}
